rust-lang/surveys

surveys/2021-annual-survey/design.md
=> Add my thoughts to 2021/design.md

surveys/notes/README.md, surveys/notes/design.md, surveys/notes/process.md
r? @rylev Covers our discussion yesterday and some things from Zulip.
=> Add some notes on the design process

surveys/notes/process.md
I didn't want to just repeat the list we have in the tracking issue so I opted more to describe the types of groups we should be targeting.
r? @nrc
=> Add list of stakeholders we should consult on the survey

surveys/2021-annual-survey/design.md, surveys/2021-annual-survey/themes.md
Signed-off-by: Nick Cameron <nrc@ncameron.org>
=> Notes on themes

surveys/2021-annual-survey/design.md, surveys/2021-annual-survey/design/contexts.md, surveys/2021-annual-survey/design/how.md, surveys/2021-annual-survey/design/purposes.md, surveys/2021-annual-survey/design/who.md, surveys/2021-annual-survey/design/why.md, surveys/2021-annual-survey/high-level-questions.md, surveys/2021-annual-survey/themes.md
This is the start of the result of @nrc and I brainstorming about the high-level goals and principles of the survey.
=> More detail in design docs

surveys/2021-annual-survey/design.md, surveys/2021-annual-survey/design/contexts.md, surveys/2021-annual-survey/design/experience.md, surveys/2021-annual-survey/design/how.md, surveys/2021-annual-survey/design/purposes.md, surveys/2021-annual-survey/design/who.md, surveys/2021-annual-survey/design/why.md, surveys/2021-annual-survey/themes.md
r? @rylev 
This isn't too interesting - fleshing out the design docs by turning notes into prose. I haven't considered justification for areas too hard, nor done any prioritisation.
=> incremental work on design

surveys/notes/survey-platforms.md
This adds the survey platform assessment found [here](https://rust-lang.zulipchat.com/#narrow/stream/294169-t-community.2Frust-survey-2021/topic/Survey.20Host).
=> Add notes on survey platform assessment

surveys/2021-annual-survey/questions.md
Most of these I just think we should remove.
=> Add some questions from previous years

surveys/2021-annual-survey/questions.md
=> Small corrections

surveys/2021-annual-survey/questions.md
Most of the questions added are marked for removal, but we'll want them in there so we can more properly discuss them.
=> Added more questions from previous year's survey

surveys/2021-annual-survey/questions.md
Commits are organised.
r? @rylev
=> Changes from Tueday's review

surveys/2021-annual-survey/questions.md
Adds justification for question originally proposed by @joshtriplett. The justification is adapted from an answer given on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/294169-t-community.2Frust-survey-2021/topic/build.20machine.20CPUs).
=> Justify question about num of cores

surveys/2021-annual-survey/questions.md, surveys/2021-annual-survey/removed-questions.md
=> Address more question review

surveys/2021-annual-survey/questions.md
=> Address comments from question review

surveys/2021-annual-survey/questions.md
- Add clarification on how often marginalized or underrepresented folks feel that their belonging to a group makes it harder to participate.
- Get more detail on the type of students
- Improve questions about human language preference
- Try to improve the question on experience with other programming languages.
=> More improvements after question review

surveys/2021-trademark-survey/README.md, surveys/2021-trademark-survey/design.md, surveys/2021-trademark-survey/questions.md
=> Add initial design for trademark survey

surveys/2021-annual-survey/questions.md
With the removal of the questions in #78 this makes a question that attempts to capture the information we would otherwise be missing out on. Loosely these are all "truisms" about Rust that we might want to consider figuring out how much users of Rust agree with.
=> Add question about truisms

surveys/2021-annual-survey/questions.md
Fixes #57 by making the question about which country someone lives in
=> Fix the where do you live question

surveys/2021-annual-survey/questions.md
I'm less thrilled about this question than I thought I would be. While theoretically this could help us better direct investment in learning programs, we realistically are covering our basis as much as we can on these fronts (both as a project and as a community). 
Thoughts?
=> Add a question about learning activities

surveys/2021-annual-survey/questions.md
=> Improve the classification of a few languages

surveys/2021-annual-survey/questions.md
=> Clarify runtimes

surveys/2021-annual-survey/questions.md
Based on feedback from entering the survey into SurveyHero
=> Make changes to questions based on Jasun's feedback

surveys/2021-annual-survey/questions.md, verifier/src/api.rs, verifier/src/main.rs, verifier/src/markdown.rs
cc @JasunC 
I also changed a few answers and questions on SurveyHero (mostly just punctuation) so that they match what's in the GitHub doc.
=> Bring the SurveyHero and GitHub versions more in sync

surveys/2021-annual-survey/questions.md
Since Taiwan is not captured already in the options...
=> Add Taiwan to the list of places to live

surveys/2021-contributor-survey/questions.md
closes https://github.com/rust-lang/surveys/issues/152
=> Fix subtle inconsistencies in questions about project governance

surveys/2021-annual-survey/questions.md
This has already been updated on SurveyHero
=> JetBrains is one word

surveys/2021-contributor-survey/questions.md
closes https://github.com/rust-lang/surveys/issues/155
=> better disambiguate tools and infra areas of contribution

surveys/2021-annual-survey/questions.md
=> Change question to be less awkward

surveys/2021-trademark-survey/questions.md
Various updates to the questions and introduction of the trademark survey,
attempting to gather data that will best inform policy development.
May be best reviewed commit-by-commit; each commit is one change.
This is net neutral on number of questions asked; it does not make the survey any longer.
=> Updates to trademark survey questions

surveys/2022-annual-survey/questions.md
=> Suggested changes for 2022 annual survey

surveys/2022-annual-survey/questions.md
=> 2022 annual survey: polishing, reordering, and questions

surveys/2022-annual-survey/questions.md
=> Apply feedback from #205

surveys/2022-annual-survey/questions.md
Here is some feedback from this [this thread (at the time of the linked message and prior)](https://rust-lang.zulipchat.com/#narrow/stream/217588-project-leads-.28public.29/topic/2022.20Annual.20Survey/near/306443817).
=> Feedback from Zulip

surveys/2022-annual-survey/questions.md
Some of these questions seem to have been unintentionally left non-optional.
=> Make more questions optional

surveys/2022-annual-survey/questions.md
=> Improve wording of question on 'true' statements

surveys/2023-annual-survey/questions.md
Incorporating suggestion at [Zulip link](https://rust-lang.zulipchat.com/#narrow/stream/402479-t-community.2Frust-survey/topic/reviewing.20changes/near/395094330).
I think the other points in that Zulip message (w.r.t. to users _desiderata_) are now covered in #243 (possibly also other questions)
r? @Kobzol
=> Add question about rust courses

surveys/2023-annual-survey/questions.md
closes #239 
to be reviewed: wording, question position and markdown format.
As mentioned in [@Kobzol comment](https://github.com/rust-lang/surveys/pull/234/files#r1348638189), it's a bit tricky to place this question where it flows well.
My ideas:
- either leave it where it is now (i.e. after "how often do you code in Rust?")
- move it up at the top of the "Rust Usage" chapter as first question
=> Add question about how often ppl code in general

surveys/2023-annual-survey/questions.md
closes #236 
question position in the survey and wording open to discussion
=> Add question about crates registries

surveys/2023-annual-survey/questions.md
This PR updates the 2023 survey Markdown file to match what is currently configured at SurveyHero. It consists mostly of flow changes (technology questions were clumped together), and some wording changes.
=> Update the survey

README.md, annual-survey.md
A simple document that writes down what we have done this year to prepare the survey.
=> Add a guide for preparing the Rust annual survey

micro-surveys.md, surveys/notes/reference.md
And also document the Markdown survey file pseudo-format.
=> Add a guide for adding microsurveys

micro-surveys.md
The five question limit was needlessly limiting, in my opinion.
=> Update micro-surveys description

surveys/2024-annual-survey/questions.md
The previous question was just... bad. This variation is hopefully more clear. I also think that it makes sense to ask this as the first question in this segment about Rust features.
Fixes: https://github.com/rust-lang/surveys/issues/248
=> Ask about user's opinion about the speed with which Rust evolves

surveys/2024-annual-survey/questions.md
Suggested [here](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29/near/474111724).
=> Add open response to the "how fast Rust evolves" question

surveys/2024-annual-survey/questions.md
Suggested [here](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29/near/474145159).
=> Add more options to learning materials

surveys/2024-annual-survey/questions.md
Discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29/near/474146673).
=> Slightly modify orphan rule answer

surveys/2024-annual-survey/questions.md
This was suggested [here](https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29/near/474073595) and I thought that it's a good idea. But apparently I forgot to send a PR for it.
=> Slightly reword "why not currently using Rust" question

surveys/2024-annual-survey/questions.md
Suggested [here](https://rust-lang.zulipchat.com/#narrow/channel/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29/near/477430602).
=> Reword "plugins" answer

verifier/Cargo.lock, verifier/Cargo.toml, verifier/src/api.rs, verifier/src/main.rs, verifier/src/markdown.rs, verifier/src/render.rs
And also add rendering code of SurveyHero questions back into the Markdown format.
=> Add checking of language variants to verifier script

surveys/2024-annual-survey/questions.md
Just-in-time modification :) This is the last stable version that we'll include in the survey.
=> Add 1.82 features

surveys/2024-annual-survey/translations/fr.md
=> French translations fixes

surveys/2024-annual-survey/translations/de.md, surveys/2024-annual-survey/translations/es.md
I didn't check the German further, just noticed this typo when I wanted to see how others translated one of the questions.
r? @Kobzol
=> Adding Spanish, fixing typo in German

surveys/2024-annual-survey/translations/de.md, surveys/2024-annual-survey/translations/fr.md
Before mergin this, let's wait for #306 to be merged
=> Fix country sorting

verifier/src/main.rs
Before it was not obvious which version in the diff is the local one (md - Markdown) and which is the remote one (sh - SurveyHero).
=> Make verifier diffs more intuitive

surveys/2024-annual-survey/translations/fr.md
With this, I consider the translations to be finished.
=> Backport a few French changes from SurveyHero

CONTRIBUTING.md
hey @Kobzol I was thinking to write here a document to help contributors orient themselves. Put here all the tribal knowledge we may have sparse on Zulip.
wdyt?
=> Add contributors guidelines

surveys/2024-annual-survey/questions.md, surveys/2024-annual-survey/translations/de.md
Let's put here all the small things we notice
r? @Kobzol
=> Last fixes

verifier/src/api.rs, verifier/src/main.rs
Before, it was hardcoded for the annual survey.
=> Allow using survey verifier for more survey kinds

surveys/micro/leadership-council-2025.md
Initial draft... needs some more work, or perhaps just cutting FIXMEs and publishing. Very open to feedback on the new approach.
cc https://rust-lang.zulipchat.com/#narrow/channel/392734-council/topic/Performance.20feedback.202025
cc @rust-lang/leadership-council
=> 2025 council survey

surveys/2025/annual-survey/questions.md
Copying the process from https://github.com/rust-lang/surveys/pull/270.
Fixes: https://github.com/rust-lang/surveys/issues/314
Fixes: https://github.com/rust-lang/surveys/issues/323
=> Bootstrap questions for the 2025 annual survey

surveys/2025/annual-survey/questions.md
https://rust-lang.zulipchat.com/#narrow/channel/213817-t-lang/topic/RFC.3A.20Rust.20Community.20Survey.202025/with/540573914
=> Add declarative macros attributes and derives to features to be stabilized

surveys/2025/annual-survey/questions.md
Discussed in https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Error.20codes.20still.20useful.3F/with/540785396.
=> Add question about error codes to the annual survey

surveys/2025/annual-survey/questions.md
It had a ton of mentions in the open answer section.
=> Add Zed to editor question in annual survey
