rust-lang/surveys

surveys/2021-annual-survey/questions.md
This adds a lot of questions to the questions.md file for the Rust at Work and Rust in Education sections. 
Some notes: 
* I added any meta commentary in block quotes. This seems to be a better approach then putting the questions themselves in the block quotes
* A lot of the questions that I added are actually marked as removed. I wanted to make sure we capture why we're removing certain questions.
=> Add more questions to Rust at Work and Rust in Education sections

surveys/2021-annual-survey/questions.md
This PR makes three improvements (all found in separate commits):
* Removes a TODO that questioned the use of calendar time in a question (and adds justification for using calendar time)
* Improves a question about which version of Rust people use by adding an option for a specific stable version.
* Improve question about why people use nightly (by adding options for use in CI and for help testing) and add the same question for beta.
=> Introduce improvements based on feedback from review session

surveys/2021-annual-survey/questions.md
Based on review with @nrc:
* Remove the idea of "drivers" from a question about IDEs
* Rework our community involvement questions to better capture the shape of how someone contributes to the Rust community
=> Address additional questions

surveys/2021-annual-survey/questions.md
- Improve question about company willingness to hire Rust devs
- Improve all the Rust education questions
- Make the `NEXT` markers more apparent
- Remove TODOs
- Add question on how easy people think it is to find a Rust job
- Ask about belonging to a marginalized group in addition to underrepresented
- A '(open response)' to all 'other' answers
=> More improvements based on question review

surveys/2021-annual-survey/questions.md
We explicitly want to differentiate have used Rust in the past vs are currently using Rust.
=> Ask explicitly about currently using Rust

surveys/2021-annual-survey/questions.md
Fixes #32 
This moves to asking specifically about how people feel about certain aspects of Rust compiler stability including things that are outside the official definition of stability (e.g., compiler performance).
=> Move stability questions to be sentiment questions

surveys/2021-annual-survey/questions.md
This will allow us to gauge interest in specific other UNIXes via the fill-in-the-blank "other" option. Right now, users of other UNIX systems aren't visible; let's try to capture the level of interest in those systems.
=> Don't group all UNIXes together

surveys/2021-annual-survey/questions.md
As discussed in the Zulip channel. the repository is the source of truth, so all changes should be done here first. This PR fixes two stylistic issues:
- Removes trailing dots from each answer
- Marks all notes as bold.
=> Style unification in the survey questions

documents/Community-Survey-FAQ.md, surveys/2021-annual-survey/questions.md
This moves the community survey from its current home [here](https://github.com/rust-community/team/wiki/State-of-the-Rust-Language-Community-Survey-FAQ) to this repo. I also changed some of the content to better reflect the current state of things. 
@Mark-Simulacrum you might want to take a look at this to ensure that things are good enough from a privacy perspective. 
cc @badboy as a representative from the community team
=> Add community survey FAQ

surveys/2022-annual-survey/questions.md
I think this is a useful question with a specific use case. There are 67 answers, so the format only makes sense if we can use a drop down box or other concise mechanism. If not, then we should refactor the answer (bucketed answers? Free text?).
r? @rylev
=> Add a question on oldest Rust version used

surveys/2022-annual-survey/questions.md
This allows us to still gauge employment, Rust usage at companies, etc. for those who don't use Rust.
=> Change flow for non-users

surveys/2022-annual-survey/questions.md
This make some questions for people who aren't employed in software disappear instead of having to repeatedly answer "no".
=> Make the Rust at Work flow better

documents/Community-Survey-FAQ.md
Btw, the URL of the last results (2022 survey) on the blog should probably contain `2022` and not `2023` (but I guess that to avoid churn and broken links, it shouldn't be changed now).
=> Add link to 2022 survey to the FAQ

surveys/2023-annual-survey/questions.md
closes #238
Ideas for more options? I guess here @alice-i-cecile has some suggestions :slightly_smiling_face: 
EDIT: [Rendered view](https://github.com/rust-lang/surveys/blob/f0c1a144b4df136689591da2e8b3326361b0a2b3/surveys/2023-annual-survey/questions.md#which-unimplemented-or-nightly-only-features-are-you-looking-for-to-be-stabilized)
=> Add question about missing features

surveys/2023-annual-survey/questions.md
Suggested edits to the 2023 survey questions from the Rust Foundation team and the board's DEI sub-committee. 
The changes we're advocating for primarily relate to the "About you" section and general survey UI/functionality as well as several more minor grammatical suggestions.
=> Suggested changes to 2023 questions from the Rust Foundation 

README.md, micro-surveys.md
This document describes an idea that was originally proposed in [this PR](https://github.com/rust-lang/surveys/pull/188) by @nrc. The survey team has recently gained access to SurveyHero, which means that we can now run our own quick surveys without the involvement of the Foundation. Together with automating the survey process as much as possible, we should now have the option to run small survey with very low latency, to provide feedback from the Rust community to Rust Project members.
Heavily inspired by https://github.com/rust-lang/surveys/pull/188, minus the monthly part.
=> Add micro-surveys proposal

report/README.md, report/requirements.txt, report/surveyhero/chart.py, report/surveyhero/parser.py, report/surveyhero/render.py, report/surveyhero/report.py, report/surveyhero/survey.py
This PR adds my Python chart and report automation scripts that were used to generate the 2023 Annual survey [analysis](https://github.com/rust-lang/blog.rust-lang.org/pull/1249). These scripts are general, and can be used in the future to generate reports, charts and a blog post for any SurveyHero survey that we perform, in a matter of minutes or hours (depending on the sizte of the survey).
=> Add analysis automation scripts

surveys/micro/leadership-council-2024.md
This adds a micro-survey for Rust project members to provide feedback on the Leadership Council. This is intended to be sent to `all@rust-lang.org`, and perhaps also post a link in #general.
cc @rust-lang/leadership-council
=> Add Leadership Council annual survey

surveys/2024-annual-survey/questions.md
This year I decided to really only copy the previous Markdown file and fix dates and Rust versions in this initial PR, to avoid long bikeshedding. We should then send individual PRs to resolve the various [issues](https://github.com/rust-lang/surveys/issues) from last year.
Closes: https://github.com/rust-lang/surveys/issues/250
Closes: https://github.com/rust-lang/surveys/issues/252
Closes: https://github.com/rust-lang/surveys/issues/254
=> Bootstrap questions for the 2024 annual survey

surveys/2024-annual-survey/questions.md
This question was originally suggested [here](https://github.com/rust-lang/surveys/pull/234/files#r1347513327).
While I think that the idea wasn't bad, I don't think that this question currently pulls its weight, so I'd like to remove it to shorten the survey. I'm basing this on the following two reasons:
1) This question only makes sense if we would do some complex cohort analysis and separate the answers of individual people. However, while SurveyHero can do this partially, we don't have access to it, and there's currently no automation (frankly, nor anyone who would have the time/motivation) that would help us with it. And without such analysis, this question is IMO not very useful.
2) Last year, we got the following answers:
In short, ~95 % people answered that they do coding or …
=> Remove question about how often do people do coding/design work

surveys/2024-annual-survey/questions.md
This would tell us more about which of those two common hardware platforms are used the most on macOS. Suggested by @lqd.
=> Split macOS into x64 and ARM variants

surveys/2024-annual-survey/questions.md
This PR moves Rust education questions (if people take a course and which learning materials do they consume) to an earlier part of the survey which already asks them about their Rust experience. It also adds a few popular questions to the "learning materials" question.
=> Move Rust education questions and add popular options

surveys/2024-annual-survey/questions.md
I think it makes more sense there. Before, we asked about OS, then about Rust versions, then about IDE, and then about Rust features (which are related to used Rust version). I think that the new ordering makes more sense.
=> Move editor question after OS question

surveys/2024-annual-survey/questions.md
It had some hits in the previous year's open answers, and given the newly released frameworks, such as Ferrocene, I think it makes sense to include it here.
=> Add "Automotive" as an answer for a technology domain

surveys/2024-annual-survey/questions.md
Before, we had a long section about Rust at work, then we asked about the user's opinion of Rust and their worries for its future, and then we went back to the job market. I think that it makes sense to ask about the job market right after asking about Rust at work. Note that this question is applicable even if the person is not currently employed.
=> Move question about job market to the end of the Rust at work section

surveys/2024-annual-survey/questions.md
There's not much that we can do with the answers of this question, but this seemed to me like a tiny change that could make the answers a bit more interesting.
No strong feeling about this though, I'm also fine to just keep it as it is.
=> Clarify answers for Rust job marker for junior/senior role

surveys/2024-annual-survey/questions.md
Suggested [here](https://github.com/rust-lang/surveys/pull/270#issuecomment-2324913643).
I would be very interested to see the results of this question. On the other hand, once the features have been stabilized, we can't really do that much about them, so in a way this doesn't matter that much? And it adds yet another question, of course.
CC @jackh726
Fixes: https://github.com/rust-lang/surveys/issues/271
=> Add question about which already stabilized features are used the most

surveys/2024-annual-survey/questions.md
I included more features, and changed the answers, because I felt like high/medium/low priority is both hard to determine and does not tell us the useful information (which features are wanted by people, which are just nice to have, which are not wanted that much and which are not even known to people).
Fixes: https://github.com/rust-lang/surveys/issues/253
=> Expand question about which features should be stabilized

surveys/2024-annual-survey/questions.md
This is a suggested merge of two similar questions about what people would like to see improved in the Rust project.
I merged these 2 questions:
- [Which of the following aspects of Rust present non-trivial problems to your programming productivity](https://github.com/rust-lang/surveys/blob/f48625bf2b4c99efc3977c8d237ae4b8e61bfcca/surveys/2024-annual-survey/questions.md?plain=1#L404-L417)
- [In your opinion, how would you prioritise work on the following aspects of Rust?](https://github.com/rust-lang/surveys/blob/f48625bf2b4c99efc3977c8d237ae4b8e61bfcca/surveys/2024-annual-survey/questions.md?plain=1#L329C1-L355)
Eliminating the latter and changing the format of the former, now a multiple choice matrix where people can express how important is each feature for them.
@Kobzol we can now …
=> Reword and merge 2 questions about Rust desiderata

surveys/2024-annual-survey/questions.md
Suggested [here](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Rust.20Annual.20Survey.202024.20RFC.20.28gathering.20feedback.29/near/474109201). We recently split the macOS platform into two (https://github.com/rust-lang/surveys/pull/281), but since then, we got a new Datadog dashboard that shows us very precisely what are the download counts of individual targets (including macOS Intel/ARM), so I'm sure if we need to split macOS anymore.
CC @lqd
=> Separate `WebAssembly` targets and merge `macOS` targets

surveys/2024-annual-survey/questions.md
It was in the last year's survey, but it was missing in the Markdown file.
=> Add Helix to IDE list

surveys/2024-annual-survey/questions.md, verifier/Cargo.lock, verifier/Cargo.toml, verifier/src/api.rs, verifier/src/main.rs
I filled in the English version of the 2024 survey into SurveyHero (uff :D). As a drive-by, I performed various typo fixes and backported changes from the survey to the Markdown file, and also revived the verifier script, which helped me uncover various small differences between the Markdown file an the content of the SurveyHero survey.
https://github.com/rust-lang/surveys/commit/a955e7620fc373527913b73a38d5a3773dd3394b is the only commit that changes the actual high-level content of the survey (it moves one question around).
=> Synchronize Markdown with SurveyHero

surveys/2024-annual-survey/translations/zh-cn.md
It should not have anything about `item`s.
=> Slightly revise translation for `associated_type_bounds`

surveys/2024-annual-survey/translations/fr.md
Plusieur reformulations pour rendre le texte plus homogène et naturel. La traduction d'origine était très mot-à-mot, parfois difficile à comprendre.
=> French translation: more natural wording for "aspects of rust" question

surveys/2024-annual-survey/translations/de.md
Fixes some typos and issues with the German translations. I have added review comments explaining some of the changes.
Additional issues which are not resolved here:
The current German translation is "Dynamische Bibliotheken/Plugins" (so libraries _or_ plugins), I assume this is wrong. But I am also not sure what exactly the English version is referring to.
In German the term "Rasse" (race) is normally used for animals, and there only being one 'human race'. If the term "Rasse" is used for humans it is often done in a racist way. Not sure what a better alternative would be here, maybe German "Abstammung" (?) or just writing "Ethnische Minderheit" (ethnic minority). Maybe another native German speaker could provide some feedback.
_(see discussion below)_
For example "Österreich" (Austria) …
=> Fix typos and issues in German 2024 translation

annual-survey.md
Page was deleted by https://github.com/rust-lang/rust-forge/pull/807
=> Remove link to deleted Rust Forge page

surveys/2024-annual-survey/translations/zh-tw.md
This PR fix some terms in zh-TW (as #335 says).
those following are wrong translated to usage of zh-CN, the correct are:
"server" => "伺服器"
"with operating systems" => "具有作業系統"
"interact" => "互動"
"coroutines" => "共常式"
"enum" => "列舉"
"trait" => "特徵"
"OOM" => "記憶體不足"
"interface" => "介面"
"SIMD" => "單指令流多資料流"
"code" => "程式碼"
"concurrency" => "並行"
"library" => "函式庫"
"support" => "支援"
"debug" => "除錯"
"visualizations" => "視覺化"
"string" => "字串"
"literals" => "字面值"
"registry" => "註冊表"
"produce" => "生產"、"製造"
"channel" => "頻道"、"管道"
"software" => "軟體"
"non-manager" => "非管理職"
"adopting" => "採用"
"memory footprint" => "記憶體使用量" (memory usage)
"project" => "專案"
=> Fix terms in zh-TW
